---
settings:
  name: ONTAP FlexArray
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents ONTAP FlexArray
    url: "/index.html"
  - section: implement-e-series
  - section: implement-third-party
  - section: install
  - title: Mentions légales
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
