---
permalink: install/reference_the_storage_errors_show_messages_and_their_resolution.html 
sidebar: sidebar 
keywords: storage, errors, show, messages, resolution 
summary: 'Lorsque les erreurs de stockage indiquent une condition d"erreur, vous devez déterminer pourquoi l"erreur s"est produite et comment la corriger.' 
---
= Les erreurs de stockage affichent des messages et leur résolution
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque `storage errors show` signale une condition d'erreur, vous devez déterminer pourquoi l'erreur s'est produite et comment la corriger.

Le tableau suivant répertorie les erreurs de configuration internes détectées par `storage errors show` et vous renvoie à des informations détaillées sur les causes de chaque erreur et sa résolution.

|===
| `storage errors show` message | Pour plus d'informations sur ce message, voir... 


 a| 
`NAME (Serial #): All paths to this array LUN are connected to the same fault domain. This is a single point of failure``.
 a| 
xref:reference_all_paths_to_an_array_lun_are_on_the_same_storage_array_controller.adoc[Tous les chemins d'accès à une LUN de baie se trouvent sur le même contrôleur de baie de stockage]



 a| 
`NAME (Serial #), port WWPN1: LUN 1 occurs more than once. LUNs cannot be reused on the same array target port`.
 a| 
xref:reference_duplicate_lun_ids_on_a_target_port.adoc[ID de LUN dupliqués sur un port cible]



 a| 
`NAME (Serial #): This array LUN is an access control LUN. It is not supported and should be masked off or disabled``.
 a| 
xref:reference_an_access_control_lun_is_presented_to_ontap.adoc[La LUN de contrôle d'accès a été présentée]



 a| 
`NAME (Serial #) This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode`.
 a| 
xref:reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.adoc[Les LUN de baie sont configurées avec des modes de basculement conflictuels]



 a| 
`NAME (Serial #): This Array LUN is only available on one path. Proper configuration requires two paths`.
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Moins de deux chemins vers une LUN de baie]



 a| 
`NAME (Serial #): This array LUN is too large and is not usable. The maximum array LUN size supported is xTB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[La LUN de la baie est trop petite ou trop grande]



 a| 
`NAME (Serial #): This array LUN is too small and is not usable. The minimum array LUN size supported is 1GB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[La LUN de la baie est trop petite ou trop grande]



 a| 
`NAME (Serial #): This Array LUN is using multiple LUN IDs. Only one LUN ID per serial number is supported`.
 a| 
xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[Les ID de LUN du même LDEV ne correspondent pas]

L'adressage de l'ensemble de volumes est incohérent



 a| 
`NAME (Serial #): This array LUN is marked foreign and has a reservation`.
 a| 
xref:reference_array_lun_is_marked_foreign_and_has_a_reservation_data_ontap_8_3_and_later.adoc[La LUN de la baie est marquée comme étrangère et possède une réservation]

|===