---
permalink: implement-third-party/concept_caution_about_using_the_vcmdb_lun.html 
sidebar: sidebar 
keywords: caution, using, vcmdb, lun 
summary: 'Pour que la base de données VCMDB (Volume Configuration Management Database) soit activée, la LUN VCMDB doit exister. La LUN VCMDB est une LUN de type commande, pas une LUN de stockage. La VCMDB est généralement mappée sur la LUN 0, mais elle peut être mappée sur une LUN de baie autre que la LUN 0.' 
---
= Avertissement concernant l'utilisation d'une LUN VCMDB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour que la base de données VCMDB (Volume Configuration Management Database) soit activée, la LUN VCMDB doit exister. La LUN VCMDB est une `command` LUN de type, pas une LUN de stockage. La VCMDB est généralement mappée sur la LUN 0, mais elle peut être mappée sur une LUN de baie autre que la LUN 0.

Si la LUN VCMDB est mappée sur un système ONTAP, ONTAP consigne régulièrement un message indiquant que la LUN VCMDB est inférieure à la taille minimale requise et indique que la LUN VCMDB est en panne. Le système ONTAP continue de fonctionner normalement après la journalisation de ce message d'erreur, mais ne peut pas utiliser la LUN.

Une LUN VCMDB ne doit pas être mappée sur un système ONTAP.
